---
name: 'Prevent file change'

"on":
  pull_request_target:
    branches: [main]

jobs:
  prevent-file-change:
    uses: sous-chefs/.github/.github/workflows/prevent-file-change.yml@5.0.6
    permissions:
      pull-requests: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    # with:
      # metadata_pattern: metadata.rb
      # metadata_trusted_authors: bmhughes,damacus,kitchen-porter,MarkGibbons,ramereth,Stromweld,xorima
      # workflow_pattern: .github/workflows
      # workflow_trusted_authors: bmhughes,damacus,kitchen-porter,MarkGibbons,ramereth,Stromweld,xorima
      # workflow_close_pr: true
      # workflow_allow_new_files: false
