---
name: "Prevent file change"

"on":
  pull_request_target:
    branches: [main]

jobs:
  prevent-file-change:
    uses: sous-chefs/.github/.github/workflows/prevent-file-change.yml@main
    permissions:
      pull-requests: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
